[project]
name = "sinitic-transfer-sent"
version = "0.1.0"
description = "Scraped reviews from OpenRice for sentiment analysis"
readme = "README.md"
dependencies = [
    "accelerate>=1.10.1",
    "datasets>=4.2.0",
    "evaluate>=0.4.6",
    "ipdb>=0.13.13",
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
    "protobuf>=6.32.1",
    "scikit-learn>=1.7.2",
    "sentencepiece>=0.2.1",
    "torch>=2.8.0",
    "transformers>=4.57.1",
    "wandb>=0.22.2",
]
