[project]
name = "sinitic-transfer"
version = "0.1.0"
description = "A short description of your project"
readme = "README.md"
dependencies = [
    "hanziconv>=0.3.2",
    "polars>=1.33.1",
    "pycantonese>=3.4.0",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.1.1",
    "sentencepiece>=0.2.1",
    "termcolor>=3.1.0",
    "thefuzz>=0.22.1",
]


[project.urls]
"Homepage" = "https://example.com/your-project"
"Repository" = "https://github.com/yourusername/your-project"
"Bug Tracker" = "https://github.com/yourusername/your-project/issues"
